# Generated by Django 4.1.1 on 2022-11-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_rubric_product_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Картика'),
        ),
    ]
