# Generated by Django 4.1.1 on 2023-01-25 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_news', '0005_alter_comment_options_product_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='like'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(help_text='Введите текст комментария', max_length=120, verbose_name='комментарий'),
        ),
    ]
